- name: uptating /e/n/i to source from interfaces.d
  ansible.builtin.template:
    src: "{{ inventory_hostname }}"
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
  when: '"leaf" in inventory_hostname'

- name: taint all cumulus nodes
  ansible.builtin.shell: "KUBECONFIG=/etc/rancher/k3s/k3s.yaml kubectl taint nodes {{ item }} cumulus={{ item }}:NoSchedule"
  loop: "{{ nodes }}"
  ignore_errors: true
  when: '"localhost" in inventory_hostname'

- name: create configmaps and deployments
  ansible.builtin.shell: "KUBECONFIG=/etc/rancher/k3s/k3s.yaml kubectl apply -k manifests/"
  when: '"localhost" in inventory_hostname'
