apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: ""
commonLabels:
  k8s-app: cumulus
resources:
- leaf01.yaml
- leaf02.yaml

generatorOptions:
 disableNameSuffixHash: true

configMapGenerator:
- name: leaf01
  files:
  - bond1.conf=bond1.conf
- name: leaf02
  files:
  - bond1.conf=bond1.conf